### ISSUE TITLE
Add Flow-Only Gauges to rfc_max_stage

### ISSUE THREAD

**Issue by MonicaStone-NOAA** [NOAA-OWP/hydrovis#312]
There are a number of AHPS gauges that only report flow, and these are currently available in the WRDS API.  Please add these flow-only gauges to the rfc_max_stage service, and update the code to use flow flood thresholds (major, moderate, etc.) for these locations.  Because the service will now contain both stage and flow gauges, it will need a name update and possibly some attribute updates as well.

**Comment by CoreyKrewson-NOAA** [comment]
@MonicaStone-NOAA do you have an example LID of one of these flow-only gauges?

**Comment by MonicaStone-NOAA** [comment]
@CoreyKrewson-NOAA Here's an example of a gauge where thresholds are defined by flow, not stage: https://water.weather.gov/ahps2/hydrograph.php?wfo=sew&gage=tolw1

**Comment by CoreyKrewson-NOAA** [comment]
awesome. Thanks!

**Comment by CoreyKrewson-NOAA** [comment]
@TylerSchrag-NOAA Did you say that you have a task in mind to convert the wrds api handler to sql? I am working on this and debating if I should just do that now or just update the python code and convert later. Any thoughts?

**Comment by CoreyKrewson-NOAA** [comment]
I am hitting a couple snags on this, mostly because of threshold values in WRDS. 

The WRDS API converts stage and streamflow behind the scenes when it can. So if I query a location that gives a stage forecast and I ask the API for streamflow forecasts, it will convert the stage to a streamflow and provide that forecast. Because there is no way to ask for gauges that are providing a pure streamflow forecast, I need to query the API for both stage and streamflow forecasts and basically combine them both but removing any duplicate sites, favoring the ones that came from the stage forecasts. In theory this should work but there are lots of examples popping up where this is flawed because of the threshold values. For example, 

Here is a forecast from TACN4
![image](https://user-images.githubusercontent.com/69687817/235258760-f4faf1d7-9369-43fa-816f-6dd90e9c791d.png)

The stage forecast is below action and thus when we query the API for all locations at action and above, we do not get this site. If we check the API, then we can see that the thresholds are correct.
![image](https://user-images.githubusercontent.com/69687817/235259085-06d3ce72-e07f-4ad8-a365-85e568a7ce43.png)

When I query for all streamflow forecast above action, the API will convert the stage to a streamflow and then compare it to the streamflow thresholds that I assume they are also converting. In many cases the stage and streamflow thresholds do not match up. If we look at this same site but for streamflow thresholds we see the following
![image](https://user-images.githubusercontent.com/69687817/235259426-7e48fae3-6550-4e78-ac56-c04b504bae0d.png)

In this case, the API is saying that the action threshold is 720 CFS but it should actually be 1,400 CFS. Because of this the converted streamflow forecast is above 720 and is thus returned by the streamflow query for all locations at action and above. 

Then when I combine the stage and streamflow forecasts above action, it adds these sites where incorrect action streamflow forecasts exist

@GautamSood-NOAA any insights into this dilemna between stage and streamflow forecasts?

**Comment by GautamSood-NOAA** [comment]
@CoreyKrewson-NOAA 

Looking at TACN4, I do see the differences between the official flow thresholds and our calculated flow thresholds.  Given the notable differences in flow vs calculated flow values, I suspect the WFO used a different rating curve (or different stage values) from what we now have available to us (NRLDB and USGS Rating Depot rating curves).

The RFC Forecast API only uses the official thresholds (not the calculated thresholds) which is why that particular location is only at action level.  

Here are the threshold values from our Location API 

![image](https://user-images.githubusercontent.com/110239408/235453108-6dbb5e9d-21f4-40d8-990a-dbe3a19f8ce9.png)

**Comment by CoreyKrewson-NOAA** [comment]
ok good to know about the forecast API using official thresholds. 

Those calculated flow thresholds looks pretty good. What rating curve is being used for that?

**Comment by GautamSood-NOAA** [comment]
If the particular LID is crosswalked to a USGS Gage, we actually use both (NWS and USGS) rating curves.  You'll see that TACN4 has 2 sets of calculated flows.  Otherwise, we just use the NWS rating curves
