### ISSUE TITLE
Update HML bucket in Ingest EC2 code to point to shared services

### ISSUE THREAD

**Issue by CoreyKrewson-NOAA** [NOAA-OWP/hydrovis#451]
- [x] Update source code on deployment bucket
- [ ] Test on TI
- [ ] Coordinate moving deployment bucket tar.gz file to UAT and Prod for switch over

**Comment by TylerSchrag-NOAA** [comment]
@AndersNilssonNoaa  - I've updated the s3://hydrovis-ti-deployment-us-east-1/ingest/owp-hml-ingester.tar.gz file to reflect the new shared services buckets in the env files at \owp-hml-ingester\hml_backup_fetcher. I did repackage on Windows with 7zip, hopefully that doesn't mess anything up.

@nickchadwick-noaa - When it's convenient timing for you, can we try deploying the ingest EC2 to TI to make sure it still works correctly with the new source code?

**Comment by AndersNilssonNoaa** [comment]
Sounds good. Ideally, we should have those bucket names get piped in from outside during the build process, but that is going to be a little harder.

**Comment by TylerSchrag-NOAA** [comment]
Yeah... guessing that can wait until WRDS joins HydroVIS, if that's still planned to happen soon-ish.

**Comment by nickchadwick-noaa** [comment]
The HML Ingest binary is actually stored in the repo [here](https://github.com/NOAA-OWP/hydrovis/blob/ti/Source/Ingest/owp-hml-ingester.tar.gz). I can update that binary from what you put in the S3 bucket.

What we could do in the future, is have the actually decompressed HML Ingester source code in the repo, then on deployment it adds those bucket variables to the source, zips it up, and puts it in the S3 bucket for the EC2 to pull down and use. We do that workflow in a handful of our Lambda functions. Just a thought, I don't know if you were wanting to store the actual source in the HydroVIS repo since it's also in VLab.
