### ISSUE TITLE
New CatFIM Observations

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/hydrovis#540]
The comment section of this issue is a space for observations about the new version of CatFIM.

**Comment by BradfordBates-NOAA** [comment]
The new Stage-Based CatFIM appears to be missing the interval polygons:

Old:
![image](https://github.com/NOAA-OWP/hydrovis/assets/69594899/7e5f7f5e-4557-403a-9aa3-fce76502eaaf)

New:
![image](https://github.com/NOAA-OWP/hydrovis/assets/69594899/6726c4a1-037c-4b0c-910f-b3f296577598)

**Comment by BradfordBates-NOAA** [comment]
In the case of site `rrtn4`, the Old Stage-Based CatFIM shows a Datum adjustment error, whereas the new version shows no such error. I am a little suspicious that the same error wasn't experienced with the new version.

**Comment by BradfordBates-NOAA** [comment]
We'll want to name the layers "Action Threshold", "Minor Threshold".

**Comment by BradfordBates-NOAA** [comment]
The new layers appear to be simplified. Is this intentional?

New:
![image](https://github.com/NOAA-OWP/hydrovis/assets/69594899/db55a3c8-4faf-4060-a3ee-3c8bd9979135)

Classic:
![image](https://github.com/NOAA-OWP/hydrovis/assets/69594899/18dba225-058f-450b-a211-d5247a555efa)

**Comment by BradfordBates-NOAA** [comment]
At ACMP1, the simplification seems to add holes to the mapping:
![image](https://github.com/NOAA-OWP/hydrovis/assets/69594899/61d88d02-5c24-4133-9ead-78217d2c10da)

**Comment by shawncrawley** [comment]
> In the case of site `rrtn4`, the Old Stage-Based CatFIM shows a Datum adjustment error, whereas the new version shows no such error. I am a little suspicious that the same error wasn't experienced with the new version.

The same error was not experienced in the new version because of how it was implemented - which I could potentially be in the wrong in... So let me explain. 

Each site has two potential sets/sources of metadata within the WRDS database: NWS and USGS. I noted that in the original on-prem implementation, the chosen metadata used for the VDatum API was determined by which source (NWS or USGS) provides a rating curve, with priority given to USGS if both exist. Site `rrtn4` does not have a USGS rating curve, but does have one from NWS (i.e. the NRLDB), and therefore the NWS metadata was used for the datum calculation as well. This does lead to an error since the NWS-provided CRS for `rrtn4` is entered in the database as "NGVD 1929". 

So in my new implementation, when it comes to getting the datum calculation metadata, I always default to using the USGS metadata whether or not there's also a USGS rating curve or not. So while there's no USGS rating curve for `rrtn4`, there is still datum metadata from USGS. So the USGS-provided CRS for `rrtn4` is "NAD83" - which is valid an thus works with the VDatum API.

I hope that makes sense and ultimately is an appropriate and value-added pivot from the original.

**Comment by BradfordBates-NOAA** [comment]
The Classic CatFIM dissolves polygons of a single magnitude and LID into one polygon, however the New CatFIM maintains discrete catchments. I think we should dissolve the New CatFIM to match Classic, since these are "steady-flow" maps.

**Comment by BradfordBates-NOAA** [comment]
Many sites in the New CatFIM do not extend as far as the Classic CatFIM. 

Example of ATIT2:
Classic
![image](https://github.com/NOAA-OWP/hydrovis/assets/69594899/1315705b-2e3f-40a2-8b57-62d4864a2df9)

New
![image](https://github.com/NOAA-OWP/hydrovis/assets/69594899/334f8742-6d25-45a3-8934-40726e2b1452)

**Comment by shawncrawley** [comment]
@BradfordBates-NOAA I fixed the issue with the extents (i.e. upstream/downstream trace) not matching. It was actually due to the upstream algorithm not being set correctly - not due to the much older (v1.1) crosswalk dataset being used. In pseudo-code, I had it programmed to add the next upstream/downstream reach if adding that reach doesn't exceed 5 miles. So say the trace was at 2 miles, but the next reach was 3.5 miles long itself. In that case, that reach wouldn't be added since adding it would exceed 5 miles. So I changed it to always add the next reach as long as the current total is less than 5 miles. Looks like that did the trick.
