### ISSUE TITLE
Add Attribute Field Aliases and Scale-Dependent Rendering to ana_high_flow_magnitude_ak_noaa

### ISSUE THREAD

**Issue by MonicaStone-NOAA** [NOAA-OWP/hydrovis#754]
After the HydroVIS 2.1.6 release, WPOD noticed that the new ana_high_flow_magnitude_ak_noaa service did not have any field aliases and was missing the scale-dependent rendering that the other Alaska services have (ana_streamflow_ak_noaa for example).  Could these be added as a hot fix to the Production service?  Thank you so much!

**Comment by DonLeisure-NOAA** [comment]
Additionally, we noticed that there is no "oid" field in the HFM - AK service. We came across this because our service monitor runs a query that depends upon this field and most of the other services also query this field. After chatting with Nick, it seems like it's probably some weird disconnect, where the REST API expects that OID field, but the service itself doesn't have it. So the service works, but a query with default Order By values don't work. Could an "oid" field, similar to the HFM -HI service, please be added? Thanks in advance!!

**Comment by derekgiardino** [comment]
Are we pausing this update completely until 2.1.7?  Just add the ana_high_flow_mag_ak_noaa with the rest of the ak services to the next build?

**Comment by KatherinePowell-NOAA** [comment]
Agreed it would be best to just push these updates with the rest of Alaska
services in the next release.

*Katherine Moore Powell, PhD*

National Water Center

Geo-Intelligence Division | Office of Water Prediction

NOAA National Weather Service

205 Hackberry Ln

Tuscaloosa, AL 35401

Cell: (813) 760-2905

***@***.*** ***@***.***>

NOAA Affiliate, Lynker
