### ISSUE TITLE
Create SD GP Service: Add code to viz_publish_service_lambda to call GP service when SD does not exist

### ISSUE THREAD

**Issue by shawncrawley** [NOAA-OWP/hydrovis#783]
Insert at this line: https://github.com/NOAA-OWP/hydrovis/blob/ti/Core/LAMBDA/viz_functions/viz_publish_service/lambda_function.py#L69
GP API Docs: https://maps-testing.water.noaa.gov/gp/sdk/rest/index.html#/02ss0000004n000000

**Comment by EdisonOrellana-NOAA** [comment]
### Update to track progress
The lines referenced above in the [lambda function](https://github.com/NOAA-OWP/hydrovis/blob/ti/Core/LAMBDA/viz_functions/viz_publish_service/lambda_function.py#L69)
```python
 if not s3_file(os.getenv('S3_BUCKET'), sd_s3_path).check_existence():
            print(f"---> {sd_s3_path} does not currently exist. Skipping.")
``` 
To add some background to this, the current situation is that when a service has not been previously manually published the `viz_publish_service` lambda *skips* over that service leaving it unpublished.

### Geoprocessing service
Instead of skipping, the proposed solution I have been testing in ti is to call a geoprocessing service to republish this service. #630 

### Remaining work
- [x] Test and verify other services
- [x] Add IaC for staging mapx files #782 
- [x] Clean code and submit PR

**Comment by EdisonOrellana-NOAA** [comment]
Done #894
